import { Game, Team, AccuracyStats, PredictionRecord, Sport } from './types';

export const SPORTS: Sport[] = [
  'NFL', 'NBA', 'MLB', 'NHL', 'Soccer',
  'NCAA Football', 'NCAA Basketball', 'UFC',
  'Boxing', 'Tennis', 'F1', 'Cricket', 'Esports'
];

const makeTeam = (
  id: string, name: string, abbr: string, sport: Sport, league: string,
  record: string, winPct: number, pr: number, offR: number, defR: number,
  elo: number, momentum: number, color: string, homeRec: string, awayRec: string,
  last5: ('W'|'L')[]
): Team => ({
  id, name, abbreviation: abbr, logo: '', sport, league, record, winPct,
  powerRanking: pr, offensiveRating: offR, defensiveRating: defR,
  netRating: offR - defR, eloRating: elo, momentum, homeRecord: homeRec,
  awayRecord: awayRec, last5, injuries: [], color,
});

export const TEAMS: Record<string, Team> = {
  'kc-chiefs': makeTeam('kc-chiefs','Kansas City Chiefs','KC','NFL','AFC West','11-4',0.733,1,28.4,18.2,1820,87,'#E31837','7-1','4-3',['W','W','L','W','W']),
  'buf-bills': makeTeam('buf-bills','Buffalo Bills','BUF','NFL','AFC East','10-5',0.667,3,27.1,19.8,1780,72,'#00338D','6-2','4-3',['W','L','W','W','L']),
  'lal-lakers': makeTeam('lal-lakers','Los Angeles Lakers','LAL','NBA','Pacific',`38-28`,0.576,7,114.2,112.8,1650,65,'#552583','21-12','17-16',['W','W','L','W','L']),
  'bos-celtics': makeTeam('bos-celtics','Boston Celtics','BOS','NBA','Atlantic','47-18',0.723,1,120.1,108.4,1780,91,'#007A33','25-7','22-11',['W','W','W','W','W']),
  'nyy-yankees': makeTeam('nyy-yankees','New York Yankees','NYY','MLB','AL East','52-29',0.642,2,5.4,3.8,1710,78,'#003087','30-12','22-17',['W','W','L','W','W']),
  'hou-astros': makeTeam('hou-astros','Houston Astros','HOU','MLB','AL West','49-32',0.605,4,5.1,4.1,1680,68,'#002D62','27-14','22-18',['L','W','W','L','W']),
  'tor-maple-leafs': makeTeam('tor-maple-leafs','Toronto Maple Leafs','TOR','NHL','Atlantic','38-21-5',0.611,3,3.2,2.7,1640,74,'#00205B','21-9-2','17-12-3',['W','W','L','W','L']),
  'col-avalanche': makeTeam('col-avalanche','Colorado Avalanche','COL','NHL','Central','40-18-6',0.656,1,3.5,2.5,1700,82,'#6F263D','22-8-2','18-10-4',['W','W','W','L','W']),
  'man-city': makeTeam('man-city','Manchester City','MAN','Soccer','Premier League','18-4-3',0.76,1,2.8,0.9,1920,88,'#6CABDD','10-2-1','8-2-2',['W','W','W','W','L']),
  'arsenal': makeTeam('arsenal','Arsenal','ARS','Soccer','Premier League','17-5-3',0.72,2,2.6,1.1,1870,81,'#EF0107','9-2-2','8-3-1',['W','W','L','W','W']),
  'jon-jones': makeTeam('jon-jones','Jon Jones','JJ','UFC','Heavyweight','27-1-1',0.94,1,92,41,1950,85,'#C8A951','14-0-1','13-1-0',['W','W','W','W','W']),
  'stipe-miocic': makeTeam('stipe-miocic','Stipe Miocic','SM','UFC','Heavyweight','20-4',0.83,3,80,62,1760,58,'#1A1A2E','10-2','10-2',['W','L','W','W','L']),
};

export const MOCK_GAMES: Game[] = [
  {
    id: 'nfl-001',
    sport: 'NFL',
    league: 'AFC Championship',
    homeTeam: TEAMS['kc-chiefs'],
    awayTeam: TEAMS['buf-bills'],
    date: '2026-06-29',
    time: '3:00 PM ET',
    venue: 'Arrowhead Stadium, Kansas City, MO',
    status: 'Upcoming',
    weather: { temp: 38, condition: 'Partly Cloudy', wind: 14, humidity: 52 },
    headToHead: {
      allTime: { home: 8, away: 5 },
      last5: { home: 3, away: 2 },
      avgScore: { home: 28.4, away: 24.1 },
      lastMeeting: 'KC 27-24 BUF (2025 Playoffs)',
    },
    odds: {
      opening: { home: -180, away: +160, spread: -3.5 },
      current: { home: -210, away: +175, spread: -4.5 },
      lineMovement: -1.0,
      publicBettingPct: { home: 63, away: 37 },
      sharpMoney: 'Home',
      expectedValue: 4.2,
    },
    prediction: {
      winner: 'Kansas City Chiefs',
      winProbability: 68.4,
      confidence: 82,
      predictedScore: { home: 27, away: 21 },
      expectedMargin: 6,
      upsetProbability: 31.6,
      playerOfMatch: 'Patrick Mahomes',
      highestImpactPlayer: 'Patrick Mahomes',
      lowestConfidenceVar: 'Buffalo pass rush performance',
      monteCarloWinRate: 69.1,
      bayesianProbability: 67.8,
      gameFlow: 'Expect a close first half with KC pulling away in the 4th quarter. Mahomes thrives in late-game situations (Top-2 all-time 4Q passer rating). Buffalo will need to establish the run early to control clock and limit KC possessions.',
      factors: [
        { label: 'Home field advantage (Arrowhead)', positive: true, weight: 8.2, detail: 'KC is 31-6 at Arrowhead in last 4 seasons' },
        { label: 'Superior offensive efficiency', positive: true, weight: 9.1, detail: 'KC ranks #1 in offensive DVOA (+24.3%)' },
        { label: 'Historical playoff dominance', positive: true, weight: 7.4, detail: 'Mahomes is 14-3 in playoff games' },
        { label: 'Better red zone efficiency', positive: true, weight: 6.8, detail: 'KC converts 72% of red zone trips vs BUF 61%' },
        { label: 'Coaching edge — Reid vs McDermott', positive: true, weight: 5.9, detail: 'Andy Reid is 8-4 vs McDermott all time' },
        { label: 'Cold weather (38°F)', positive: false, weight: -4.1, detail: 'Bills historically perform better in cold weather' },
        { label: 'Buffalo defensive pressure', positive: false, weight: -5.3, detail: 'BUF ranked #4 in sack rate; KC OL questionable' },
        { label: 'Josh Allen dual-threat risk', positive: false, weight: -6.1, detail: "Allen's rushing adds 180+ expected yards" },
      ],
    },
  },
  {
    id: 'nba-001',
    sport: 'NBA',
    league: 'NBA Regular Season',
    homeTeam: TEAMS['bos-celtics'],
    awayTeam: TEAMS['lal-lakers'],
    date: '2026-06-26',
    time: '7:30 PM ET',
    venue: 'TD Garden, Boston, MA',
    status: 'Upcoming',
    headToHead: {
      allTime: { home: 146, away: 166 },
      last5: { home: 3, away: 2 },
      avgScore: { home: 112.4, away: 108.9 },
      lastMeeting: 'BOS 118-112 LAL (Jan 2026)',
    },
    odds: {
      opening: { home: -220, away: +185, spread: -5.5 },
      current: { home: -240, away: +200, spread: -6.0 },
      lineMovement: -0.5,
      publicBettingPct: { home: 71, away: 29 },
      sharpMoney: 'Home',
      expectedValue: 5.8,
    },
    prediction: {
      winner: 'Boston Celtics',
      winProbability: 74.2,
      confidence: 87,
      predictedScore: { home: 119, away: 108 },
      expectedMargin: 11,
      upsetProbability: 25.8,
      playerOfMatch: 'Jayson Tatum',
      highestImpactPlayer: 'Jayson Tatum',
      lowestConfidenceVar: 'LeBron James health/minutes',
      monteCarloWinRate: 75.4,
      bayesianProbability: 73.9,
      gameFlow: 'Celtics pace advantage will be decisive. Boston\'s 3-point shooting (42.1%, #1 NBA) vs Lakers perimeter defense (ranked 22nd) creates a structural mismatch. Expect a close first quarter followed by a Celtics surge in Q2.',
      factors: [
        { label: 'Top-rated defense (108.4 DRTG)', positive: true, weight: 9.4, detail: 'Best defensive rating in the NBA this season' },
        { label: 'Elite 3-point shooting', positive: true, weight: 8.7, detail: 'Celtics shoot 42.1% from 3 (NBA #1)' },
        { label: 'Home court + crowd energy', positive: true, weight: 7.1, detail: 'TD Garden: 18-4 record this season' },
        { label: 'Depth advantage (9-man rotation)', positive: true, weight: 6.2, detail: 'Lakers heavily rely on LeBron/AD 2-man game' },
        { label: 'Tatum vs Lakers history', positive: true, weight: 5.8, detail: 'Tatum averages 31.2 PPG vs LAL last 5 games' },
        { label: 'LeBron motivation factor', positive: false, weight: -5.4, detail: 'LeBron historically elevates vs elite competition' },
        { label: 'Lakers fast-break potential', positive: false, weight: -4.2, detail: 'AD dominates in transition scoring' },
        { label: 'Celtics back-to-back fatigue', positive: false, weight: -3.8, detail: 'Second game in 2 nights for Boston' },
      ],
    },
  },
  {
    id: 'mlb-001',
    sport: 'MLB',
    league: 'AL East',
    homeTeam: TEAMS['nyy-yankees'],
    awayTeam: TEAMS['hou-astros'],
    date: '2026-06-27',
    time: '7:05 PM ET',
    venue: 'Yankee Stadium, New York, NY',
    status: 'Upcoming',
    weather: { temp: 79, condition: 'Clear', wind: 8, humidity: 61 },
    headToHead: {
      allTime: { home: 218, away: 204 },
      last5: { home: 3, away: 2 },
      avgScore: { home: 5.2, away: 4.8 },
      lastMeeting: 'NYY 4-2 HOU (May 2026)',
    },
    odds: {
      opening: { home: -145, away: +125, spread: -1.5 },
      current: { home: -160, away: +140, spread: -1.5 },
      lineMovement: -0.15,
      publicBettingPct: { home: 58, away: 42 },
      sharpMoney: 'Split',
      expectedValue: 1.4,
    },
    prediction: {
      winner: 'New York Yankees',
      winProbability: 58.3,
      confidence: 63,
      predictedScore: { home: 5, away: 3 },
      expectedMargin: 2,
      upsetProbability: 41.7,
      playerOfMatch: 'Gerrit Cole',
      highestImpactPlayer: 'Gerrit Cole',
      lowestConfidenceVar: 'Bullpen performance in late innings',
      monteCarloWinRate: 57.9,
      bayesianProbability: 58.7,
      gameFlow: 'Pitching-dominant game expected. Gerrit Cole (2.91 ERA, 189 Ks) vs Houston lineup that struggles vs elite right-handers (.238 batting avg). Game likely decided in 7th-9th innings based on bullpen match-ups.',
      factors: [
        { label: 'Gerrit Cole starting (2.91 ERA)', positive: true, weight: 9.2, detail: '7 quality starts in last 8 outings' },
        { label: 'Home field advantage', positive: true, weight: 5.8, detail: 'Yankees 30-12 at Yankee Stadium this season' },
        { label: 'Houston bullpen fatigue', positive: true, weight: 4.7, detail: 'HOU bullpen used heavily in last 3 games' },
        { label: 'Yankees power hitting vs HOU starters', positive: true, weight: 6.1, detail: 'NYY sluggers hit .291 vs HOU rotation historically' },
        { label: 'Close game — high variance', positive: false, weight: -6.8, detail: 'MLB predictions inherently uncertain; 60%+ is strong' },
        { label: 'Astros lineup quality', positive: false, weight: -5.2, detail: 'HOU ranks 3rd in wOBA vs RHP (.341)' },
        { label: 'NYY closer availability', positive: false, weight: -4.1, detail: 'Primary closer pitched back-to-back' },
      ],
    },
  },
  {
    id: 'nhl-001',
    sport: 'NHL',
    league: 'NHL Western Conference',
    homeTeam: TEAMS['col-avalanche'],
    awayTeam: TEAMS['tor-maple-leafs'],
    date: '2026-06-28',
    time: '9:00 PM ET',
    venue: 'Ball Arena, Denver, CO',
    status: 'Upcoming',
    headToHead: {
      allTime: { home: 18, away: 14 },
      last5: { home: 3, away: 2 },
      avgScore: { home: 3.4, away: 2.8 },
      lastMeeting: 'COL 4-3 OT TOR (Feb 2026)',
    },
    odds: {
      opening: { home: -165, away: +145, spread: -1.5 },
      current: { home: -185, away: +158, spread: -1.5 },
      lineMovement: -0.2,
      publicBettingPct: { home: 67, away: 33 },
      sharpMoney: 'Home',
      expectedValue: 3.1,
    },
    prediction: {
      winner: 'Colorado Avalanche',
      winProbability: 64.8,
      confidence: 76,
      predictedScore: { home: 4, away: 2 },
      expectedMargin: 2,
      upsetProbability: 35.2,
      playerOfMatch: 'Nathan MacKinnon',
      highestImpactPlayer: 'Nathan MacKinnon',
      lowestConfidenceVar: 'Goaltending matchup variance',
      monteCarloWinRate: 65.3,
      bayesianProbability: 64.4,
      gameFlow: 'MacKinnon at altitude creates a near-impossible matchup for Toronto defenders. Expect an up-tempo game favoring Colorado\'s skating depth. Toronto\'s best chance is goaltending performance and capitalizing on powerplay opportunities.',
      factors: [
        { label: 'Altitude advantage (5,280 ft)', positive: true, weight: 8.4, detail: 'COL outscores visiting teams +0.6 G/game vs altitude-naive opponents' },
        { label: 'MacKinnon in elite form', positive: true, weight: 9.1, detail: '1.78 points/game over last 12 games' },
        { label: 'COL 5v5 xGF% (57.2%)', positive: true, weight: 7.8, detail: 'Best expected goals differential in the West' },
        { label: 'TOR back-to-back game', positive: true, weight: 5.3, detail: 'Toronto played last night; travel from Eastern timezone' },
        { label: 'Goaltending variance (high SD)', positive: false, weight: -5.9, detail: 'NHL goaltending swings can erase all other advantages' },
        { label: 'Matthews/Marner powerplay', positive: false, weight: -5.1, detail: 'TOR PP ranks 5th in NHL (24.8%)' },
      ],
    },
  },
  {
    id: 'soccer-001',
    sport: 'Soccer',
    league: 'Premier League',
    homeTeam: TEAMS['man-city'],
    awayTeam: TEAMS['arsenal'],
    date: '2026-06-28',
    time: '12:30 PM ET',
    venue: 'Etihad Stadium, Manchester, UK',
    status: 'Upcoming',
    weather: { temp: 62, condition: 'Overcast', wind: 12, humidity: 74 },
    headToHead: {
      allTime: { home: 24, away: 18 },
      last5: { home: 3, away: 1 },
      avgScore: { home: 2.1, away: 1.4 },
      lastMeeting: 'MCI 3-1 ARS (Feb 2026)',
    },
    odds: {
      opening: { home: -175, away: +420, spread: 0 },
      current: { home: -190, away: +450, spread: 0 },
      lineMovement: -0.15,
      publicBettingPct: { home: 72, away: 14 },
      sharpMoney: 'Home',
      expectedValue: 2.8,
    },
    prediction: {
      winner: 'Manchester City',
      winProbability: 64.1,
      confidence: 79,
      predictedScore: { home: 2, away: 1 },
      expectedMargin: 1,
      upsetProbability: 14.2,
      playerOfMatch: 'Erling Haaland',
      highestImpactPlayer: 'Erling Haaland',
      lowestConfidenceVar: 'Arsenal counter-attack conversion rate',
      monteCarloWinRate: 64.8,
      bayesianProbability: 63.7,
      gameFlow: 'City will dominate possession (expected 62%). The key battleground is Arsenal\'s defensive block vs Haaland\'s movement. Arsenal\'s best path: absorb pressure and hit on the counter through Martinelli/Saka channels.',
      factors: [
        { label: 'City possession superiority (62% avg)', positive: true, weight: 8.2, detail: 'Arsenal concedes 1.9 xGA/90 vs high-possession teams' },
        { label: 'Haaland vs Arsenal (8 goals in 5)', positive: true, weight: 9.3, detail: 'Statistical outlier performance in this fixture' },
        { label: 'Home advantage + Etihad atmosphere', positive: true, weight: 6.1, detail: 'City W/L/D: 10/2/1 at Etihad this season' },
        { label: 'Arsenal missing Saliba (suspension)', positive: true, weight: 7.4, detail: 'Arsenal\'s best CB absent; defensive vulnerability' },
        { label: 'Arsenal counter-attack threat', positive: false, weight: -6.2, detail: 'Saka/Martinelli among fastest attackers in PL' },
        { label: 'City midfield fitness concerns', positive: false, weight: -4.8, detail: 'Rodri game-time decision after knock' },
        { label: 'Draw probability significant (21.7%)', positive: false, weight: -4.1, detail: 'Arsenal plays for the point in big away fixtures' },
      ],
    },
  },
  {
    id: 'ufc-001',
    sport: 'UFC',
    league: 'UFC Heavyweight Championship',
    homeTeam: TEAMS['jon-jones'],
    awayTeam: TEAMS['stipe-miocic'],
    date: '2026-06-30',
    time: '10:00 PM ET',
    venue: 'T-Mobile Arena, Las Vegas, NV',
    status: 'Upcoming',
    headToHead: {
      allTime: { home: 1, away: 0 },
      last5: { home: 1, away: 0 },
      avgScore: { home: 0, away: 0 },
      lastMeeting: 'Jones def. Miocic by TKO Rd 3 (2023)',
    },
    odds: {
      opening: { home: -380, away: +300, spread: 0 },
      current: { home: -420, away: +340, spread: 0 },
      lineMovement: -0.4,
      publicBettingPct: { home: 78, away: 22 },
      sharpMoney: 'Home',
      expectedValue: 1.9,
    },
    prediction: {
      winner: 'Jon Jones',
      winProbability: 79.3,
      confidence: 85,
      predictedScore: { home: 0, away: 0 },
      expectedMargin: 0,
      upsetProbability: 20.7,
      playerOfMatch: 'Jon Jones',
      highestImpactPlayer: 'Jon Jones',
      lowestConfidenceVar: 'Stipe\'s boxing accuracy in close range',
      monteCarloWinRate: 79.8,
      bayesianProbability: 78.9,
      gameFlow: 'Jones will seek to neutralize Stipe\'s boxing with wrestling and clinch work. If Jones keeps it standing, Stipe has a puncher\'s chance. Round 1-2 feeling out expected; Jones likely to impose will from Round 3+.',
      factors: [
        { label: 'Jones grappling superiority', positive: true, weight: 9.6, detail: '24.1 takedown attempts in HW fights; 68% completion' },
        { label: 'Better physical attributes (reach, frame)', positive: true, weight: 7.2, detail: 'Jones +4" reach; superior lateral movement' },
        { label: 'Jones won first meeting (TKO R3)', positive: true, weight: 8.1, detail: 'Demonstrated clear gameplan advantage' },
        { label: 'Stipe 42 years old', positive: true, weight: 6.4, detail: 'Age/recovery curve disadvantage in 5-round fight' },
        { label: 'Stipe elite boxing (1.9 acc/min)', positive: false, weight: -7.8, detail: '1 punch KO power; Jones has been hurt before' },
        { label: 'Jones inactivity (18 months)', positive: false, weight: -5.9, detail: 'Ring rust is a real variable at this level' },
      ],
    },
  },
];

export const ACCURACY_STATS: AccuracyStats = {
  overall: 68.4,
  last30Days: 71.2,
  bySport: {
    NBA: 72.1, NFL: 69.8, MLB: 61.4, NHL: 65.3,
    Soccer: 67.8, UFC: 71.4, Tennis: 73.2, 'NCAA Basketball': 68.9,
  },
  byConfidenceTier: [
    { tier: '90-100%', accuracy: 84.2, count: 247 },
    { tier: '80-89%', accuracy: 76.8, count: 891 },
    { tier: '70-79%', accuracy: 68.4, count: 1432 },
    { tier: '60-69%', accuracy: 61.7, count: 2104 },
    { tier: '50-59%', accuracy: 54.2, count: 1876 },
  ],
  brierScore: 0.194,
  logLoss: 0.612,
  rocAuc: 0.731,
  upsetAccuracy: 42.8,
  avgMarginError: 4.2,
  totalPredictions: 6550,
  calibrationData: [
    { predicted: 50, actual: 51.2 },
    { predicted: 55, actual: 54.8 },
    { predicted: 60, actual: 61.7 },
    { predicted: 65, actual: 64.2 },
    { predicted: 70, actual: 68.4 },
    { predicted: 75, actual: 76.8 },
    { predicted: 80, actual: 78.9 },
    { predicted: 85, actual: 83.1 },
    { predicted: 90, actual: 84.2 },
  ],
};

export const PREDICTION_HISTORY: PredictionRecord[] = [
  { id: 'p1', gameId: 'nba-h1', sport: 'NBA', prediction: 'Boston Celtics', confidence: 84, actual: 'Boston Celtics', correct: true, margin: 8, date: '2026-06-20' },
  { id: 'p2', gameId: 'nfl-h2', sport: 'NFL', prediction: 'Kansas City Chiefs', confidence: 78, actual: 'Kansas City Chiefs', correct: true, margin: 7, date: '2026-06-19' },
  { id: 'p3', gameId: 'mlb-h3', sport: 'MLB', prediction: 'New York Yankees', confidence: 61, actual: 'Houston Astros', correct: false, margin: -2, date: '2026-06-18' },
  { id: 'p4', gameId: 'nhl-h4', sport: 'NHL', prediction: 'Colorado Avalanche', confidence: 72, actual: 'Colorado Avalanche', correct: true, margin: 2, date: '2026-06-17' },
  { id: 'p5', gameId: 'soc-h5', sport: 'Soccer', prediction: 'Manchester City', confidence: 77, actual: 'Manchester City', correct: true, margin: 1, date: '2026-06-16' },
  { id: 'p6', gameId: 'ufc-h6', sport: 'UFC', prediction: 'Jon Jones', confidence: 83, actual: 'Jon Jones', correct: true, margin: 0, date: '2026-06-15' },
  { id: 'p7', gameId: 'nba-h7', sport: 'NBA', prediction: 'Los Angeles Lakers', confidence: 57, actual: 'Boston Celtics', correct: false, margin: -11, date: '2026-06-14' },
  { id: 'p8', gameId: 'nfl-h8', sport: 'NFL', prediction: 'Buffalo Bills', confidence: 65, actual: 'Buffalo Bills', correct: true, margin: 3, date: '2026-06-13' },
];
